global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    dns_sd_configs:
      - names:
          - 'tasks.api-gateway'
        type: 'A'
        port: 3000

  - job_name: 'auth-service'
    dns_sd_configs:
      - names:
          - 'tasks.auth-service'
        type: 'A'
        port: 3001

  - job_name: 'ride-service'
    dns_sd_configs:
      - names:
          - 'tasks.ride-service'
        type: 'A'
        port: 3002

  - job_name: 'driver-service'
    dns_sd_configs:
      - names:
          - 'tasks.driver-service'
        type: 'A'
        port: 3003

  - job_name: 'payment-service'
    dns_sd_configs:
      - names:
          - 'tasks.payment-service'
        type: 'A'
        port: 3004

  - job_name: 'notification-service'
    dns_sd_configs:
      - names:
          - 'tasks.notification-service'
        type: 'A'
        port: 3005

  - job_name: 'ai-service'
    dns_sd_configs:
      - names:
          - 'tasks.ai-service'
        type: 'A'
        port: 3006
